services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  sessions:
    image: 'sessions'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

