name: Lint

on:
  push:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  lint:
    runs-on: ubuntu-latest
    working-directory: ./authentication
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U black==23.12.1 pydocstyle
          pip install -U -r requirements.txt

      - name: Lint with black
        run: |
          black --check .

      - name: Lint with pydocstyle
        run: |
          pydocstyle .

      - name: Lint with pyright
        uses: jakebailey/pyright-action@v2
