name: Lint Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -U black==23.12.1 pydocstyle
          pip install -U -r requirements.txt

      - name: Lint with black
        working-directory: ./backend
        run: |
          black --check .

      # Uncomment the following if we eventually decide to document our code
      # - name: Lint with pydocstyle
        # working-directory: ./backend
        # run: |
          # pydocstyle .

      - name: Lint with pyright
        uses: jakebailey/pyright-action@v2
        with:
          working-directory: ./backend

      - name: Run pytest
        working-directory: ./backend
        run: |
          pytest
