name: Flutter Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Clone repository
          uses: actions/checkout@v4

        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version: 3.22.0

        - name: Get all Flutter Packages
          run: flutter pub get
          working-directory: ./flutter_application

        - name: Make envfile
          uses: SpicyPizza/create-envfile@v2.0
          with:
            envkey_BACKEND_API_URL: http://example.com
            directory: ./flutter_application
            file_name: .env
            fail_on_empty: false
            sort_keys: false

        - name: Mocks
          run: flutter pub run build_runner build

        - name: Run Flutter Test
          run: flutter test
          working-directory: ./flutter_application
